### ISSUE TITLE
Pick a better name

### ISSUE THREAD

**Issue by alanmoo** [alanmoo/Portland-Condo#1]
We need a better name for this place. Something witty that we can use on Swarm, Facebook events, etc.

**Comment by alanmoo** [comment]
@ChrissyMoo what do you think?

**Comment by ChrissyMoo** [comment]
Named Condo the Sparkle Moose Lounge!  

Chosen after doing a mind map w/ Heather and Adam, and polling friends.

(2nd choice was the Flashy Flamingo Flat - may still use in some capacity...)
