### ISSUE TITLE
Determine washer/dryer

### ISSUE THREAD

**Issue by alanmoo** [alanmoo/Portland-Condo#8]
It seems like it's a sale time of year. The Sweet Home [recommends](http://thesweethome.com/reviews/the-best-washer-and-dryer/) the LG WM3570HWA washer and LG DLEX3570W electric dryer. Best Buy/Home Depot have sales on similar models, do we want these specifically though? Do we need to pull the trigger sooner rather than later?

**Comment by ChrissyMoo** [comment]
http://www.homedepot.com/p/LG-Electronics-4-3-DOE-cu-ft-High-Efficiency-Front-Load-Washer-in-Graphite-Steel-ENERGY-STAR-WM3570HVA/205140113

http://www.bestbuy.com/site/lg-4-5-cu-ft-12-cycle-front-loading-washer-white/5149407.p?id=bb5149407&skuId=5149407
(3670 - but no turbo wash?)

**Comment by ChrissyMoo** [comment]
Chose LG WM3570HWA washer and LG DLEX3570W electric dryer.  Dan ordering through appliance guy - total cost $1600 - he is covering $1000, we owe Dan $600.
